name: Lint markdown & check links

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: '**/*.md'
          config: '.markdownlint.jsonc'

  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lychee link checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --verbose --max-concurrency 5 './**/*.md'
          fail: true
